### ISSUE TITLE
Context box treats new-lines as separate prompts

### ISSUE THREAD

**Issue by dskarbek** [Kvadratni/goose-intellij#10]
When using the Option-G context input, I can hit shift-enter to move to a new line, but then it treats each line as a separate prompt being submitted to Goose.  It should concat all the lines together as one prompt.

**Comment by Kvadratni** [comment]
HONK! GOOSE WILL FIX IT! (this message was generated by goose while fixing the issue)

**Comment by Kvadratni** [comment]
closed with https://github.com/Kvadratni/goose-intellij/pull/14
