### ISSUE TITLE
Can enter multiple lines in the Goose terminal

### ISSUE THREAD

**Issue by dskarbek** [Kvadratni/goose-intellij#12]
I tried to type some prompt and then shift-enter to paste some more data on the next line in the Goose terminal window and it submitted the prompt before I was able to enter the additional data.  I'd like to be able to enter multi line prompts.

**Comment by Kvadratni** [comment]
This seems to be an issue in intellij terminals in general.

**Comment by Kvadratni** [comment]
Update- goose uses `prompt toolkit` which binds option+enter as newline. This works in intellij too.
