### ISSUE TITLE
Context prompt box doesn't scroll

### ISSUE THREAD

**Issue by dskarbek** [Kvadratni/goose-intellij#9]
If I highlight some text and press Option-G to bring up the Ask Goose box, and then type more text than will fit in the box, it does not scroll to the right following your input.  I can not get it to shift over in any way.  It should scroll, or better yet, auto-wrap.

**Comment by Kvadratni** [comment]
HONK! GOOSE WILL FIX IT! (this message was generated by goose while fixing the issue)

**Comment by Kvadratni** [comment]
HONK! GOOSE WILL FIX IT! (this message was generated by goose while fixing the issue)

**Comment by Kvadratni** [comment]
fixed with https://github.com/Kvadratni/goose-intellij/pull/14
